version: '3.7'

services:
    php-httpd:
        image: php:8.1-apache
        ports:
            - 80:80
        volumes:
            - "/home/rick/code/webroot:/var/www/html"

    mariadb:
        image: mariadb:10.6.5
        volumes:
            - mariadb-volume:/var/lib/mysql
        environment:
            TZ: "America/Chicago"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "rootpwd"
            MYSQL_USER: 'dbuser'
            MYSQL_PASSWORD: 'dbpass'
            MYSQL_DATABASE: 'db'

volumes:
    mariadb-volume:
