version: '3.9'

services:
    php-apache:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3000:80
        volumes:
              # change the first part of this path to the location of your code on your computer
            - "/Users/wilczeschin/Documents/IT/IT_2830/student_docker/Module_3:/var/www/php"

    mariadb:
        image: mariadb:10.6.5
        ports:
            - 3306:3306
        volumes:
            - db-volume:/var/lib/mysql
        environment:
            TZ: "America/Chicago"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "rootpwd"
            MYSQL_USER: 'dbuser'
            MYSQL_PASSWORD: 'dbpass'
            MYSQL_DATABASE: 'db'

volumes:
    db-volume:
