version: '3.9'

services:
    php-apache:
        build:
          dockerfile: Dockerfile
        ports:
            - 3000:80
        volumes:
            - "/path/to/www:/var/www/"

    mariadb:
        image: mariadb:10.6.5
        volumes:
            - db-volume:/var/lib/mysql
        environment:
            TZ: "America/Chicago"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "rootpwd"
            MYSQL_USER: 'dbuser'
            MYSQL_PASSWORD: 'dbpass'
            MYSQL_DATABASE: 'db'

volumes:
    db-volume:
